### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘rjags’

### ISSUE THREAD

**Issue by MoMaz123** [okezie94/mrbayes#16]
Hi guys, 
I am running 

library(mrbayes)

dat <-
  mr_format(
    rsid = expo$SNP,
    xbeta = expo$beta.exposure,
    ybeta = Out$beta.outcome,
    xse = expo$se.exposure,
    yse = Out$se.outcome
  )

fit <- mr_egger_rjags(dat)

getting  this  error 

Error in loadNamespace(name) : there is no package called ‘rjags’

I have restarted R, still same error. 

It  would  be  appreciated if you could help me with  this  error. Thanks,

**Comment by remlapmot** [comment]
You just need to install the rjags package, so run in R
``` r
install.packages('rjags')
```

**Comment by MoMaz123** [comment]
Great thanks, I installed just now. 

after
fit <- mr_egger_rjags(dat)

 I have this error,
 
Error: .onLoad failed in loadNamespace() for 'rjags', details:
  call: fun(libname, pkgname)
  error: Failed to locate any version of JAGS version 4

The rjags package is just an interface to the JAGS library
Make sure you have installed JAGS-4.x.y.exe (for any x >=0, y>=0) from
http://www.sourceforge.net/projects/mcmc-jags/files


BTW, I can run the Stan very well, 

egger_fit <- mr_egger_stan(dat, n.burn = 500, n.iter = 1000)
print(egger_fit)

If there is any difference between them stan and jags output?

Thanks in advance!

**Comment by remlapmot** [comment]
After you installed the rjags package it's probably best to close and reopen RStudio (or however you are running R).

The Stan and JAGS output should be very similar.

**Comment by MoMaz123** [comment]
Thanks Tom, appreciated!

**Comment by remlapmot** [comment]
I forgot to say that if you're on Windows or macOS that you will need to install the JAGS program itself.

The installer files are available from https://sourceforge.net/projects/mcmc-jags/files/ . 

It's probably best to close R/RStudio while you install JAGS. Hopefully the rjags package will then detect your JAGS installation.
